version: "3"

tasks:
  test: go test ./...
  coverage: go test -v -coverprofile=profile.cov ./...
  build: go build -o typex2
  examples:
    - task: build
    - ./typex2 -l typescript ./examples
    - ./typex2 -l dart ./examples
    - ./typex2 -l swift ./examples
    - ./typex2 -l kotlin ./examples
